README.md
* Move the thanks to contributors to the contributing section
* Introduce the new "About thoughtbot" section.
=> Introduce About thoughtbot section

README.md
GitHub diff: https://github.com/thoughtbot/paperclip/pull/1850/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8
=> SVGs are prettier than PNGs in the README

lib/paperclip/locales/tr.yml
=> Added locale file for Turkish.

lib/paperclip/storage/s3.rb
This resolves the issue created by merging the v4.3 branch back to master.
=> Fix merge problem with S3 storage

paperclip.gemspec
mimemagic 0.3.1 has been released.
=> Relax mimemagic version constraint to ~> 0.3.0

NEWS, lib/paperclip/version.rb
Updates to NEWS and lib/paperclip/version.rb
=> update version to 4.3.6 [ci skip]

README.md
=> Update example to add mime-types to file extensions

features/step_definitions/s3_steps.rb, lib/paperclip/storage/s3.rb, spec/paperclip/storage/s3_spec.rb
We don't support AWS SDK v1 any longer.
=> Paperclip::Storage::S3 simplification

cucumber/paperclip_steps.rb, lib/paperclip/storage/s3.rb, spec/paperclip/storage/s3_spec.rb
cc @kitop in case you spot more pieces.
=> Removes dead code

README.md
for better visibility and better User experience of documentation
=> link in Readme to source code of Paperclip::Processor

lib/paperclip/helpers.rb
=> Fix outdated method description in helper module

CONTRIBUTING.md, README.md, lib/paperclip/errors.rb, lib/paperclip/helpers.rb
When contributing for the first time, it's easy to miss that you need to have ImageMagick and Ghostscript installed on your machine. I just added some documentation to the contribution guidelines and the error comments to reinforce this. (And also a link to the contribution page in the README)
=> Clarifying contributions.

NEWS, README.md
Added links to referenced tools for beginners, blocked out User model further in Quick Start
=> README elucidation for Ruby beginners

lib/paperclip/content_type_detector.rb
=> Automatically close file while checking mime type

NEWS, lib/paperclip.rb, lib/paperclip/deprecations.rb, lib/paperclip/version.rb, spec/paperclip/deprecations_spec.rb, spec/paperclip/paperclip_spec.rb, spec/support/deprecations.rb
Adds deprecation warnings, as v5 is ready (in beta version right now).
=> Release version 4.3.7

NEWS, README.md, lib/paperclip/version.rb
=> Release v5.0.0

README.md
=> Update docs to mention ImageMagick resource limits

features/step_definitions/rails_steps.rb, paperclip.gemspec
=> Fix a build

NEWS, lib/paperclip/version.rb
=> Bump to 5.2.1

README.md
=> Rename FactoryGirl to FactoryBot

MIGRATING.md
Explain some lessons learned from successfully migrating an application
from Paperclip to ActiveStorage.
Replace links to `master` or `edgeguides.rubyonrails.org` with versions
locked to `v5.2`.
=> Expand upon Migration Documentation

MIGRATING.md
This is a combination of [a comment from @sankage] and [a gist by
@colinpetruno]. Many thanks to them for sharing their discoveries.
[a comment from @sankage]: https://github.com/thoughtbot/paperclip/pull/2568#issuecomment-381629629
[a gist by @colinpetruno]: https://gist.github.com/colinpetruno/037de4fafa4cff695b1d7905cd6fd7c2
=> Syntax fixes for DB migration

MIGRATING.md, README.md
At RailsConf 2019, Colleen Schnettler gave a fantastic talk on her
real-world experience migrating from Paperclip to ActiveStorage, titled
"How to migrate to Active Storage without losing your mind".
In it she goes through the steps before and after a migration, and also
talks through the details of the migration guide, along with some
corrections.
Link to the ConfFreaks video of this talk on YouTube so more
video-minded folks can learn about the migration in a manner that is
more comfortable.
=> Link to Colleen Schnettler's talk
