thoughtbot/paperclip

paperclip.gemspec
Updated gemspec to require aws-sdk gem ~> 1.6
=> Updated gemspec to fix issue #1729

lib/paperclip/thumbnail.rb, spec/paperclip/tempfile_factory_spec.rb, spec/paperclip/thumbnail_spec.rb
* also includes a test for TempfileFactory to be sure it does not revert to similar behavior
=> Fix for Errno::ENAMETOOLONG in Thumbnails

README.md, lib/paperclip/storage/s3.rb
The `aws-sdk` development dependency was updated to `~> 1.6` in #1816
to resolve issues with the creation of 0-byte files on S3 (see #1729).
However, there is no runtime dependency on `aws-sdk`, and the
documentation still suggests that users install an earlier version of
`aws-sdk` that produces the problems in the referenced issue.
This commit updates the docs to recommend the use of `aws-sdk` `~> 1.6`
with Paperclip.
=> Use Updated Version of `aws-sdk` in Docs [ci skip]

README.md
The task (as specified in the current form) did not work for me (on Rails 4.2.0 and Capistrano 3.3.5 with rbenv). I changed the task so that it uses the same standards as Capistrano's own tasks.
This now works for my setup.
=> Updated the `build missing styles` Capistrano task

lib/paperclip.rb
See https://github.com/rails/rails/pull/18196 and https://github.com/rails/rails-html-sanitizer/issues/26 for a discussion of why this is necessary.
Not sure why this is failing on travis but it doesn't look like it's because of this change.
=> If Rails is defined but Rails::Railtie is not, don't try to load the Railtie

README.md
ImageMagick has a Ubuntu Launchpad package available to install and ready to use. This will help Ubuntu users to find the correct version of ImageMagick right of the box. :+1:
=> [ci skip] Add Ubuntu install instructions

lib/paperclip/geometry_parser_factory.rb, spec/paperclip/geometry_spec.rb
According to the [ImageMagick documentation](http://www.imagemagick.org/Usage/resize/#pixel) the `@` flag is a special case that can be used in conjunction with `>` to prevent IM from scaling an image up. The `<` flag is ignored when using `@`.
This fixes the issue I reported in #1851, which I believe was incorrectly marked as duplicate.
=> Fix GeometryParser for '@>' special case

NEWS, README.md, lib/paperclip/version.rb
Removes note for running paperclip in EOL'd version of Rails (2.3).
This release got messy because history in master got intertwined commits for Rails 5, the backport to 3.2, and normal development. If we are not going to rebase Pull Requests with many "messy" commits, it's going to be good to use merge commits rather than rebasing them in, so it's easier to revert.
cc @jyurek @sikachu @iwz. Will release the new gem after your +1.
=> Release version v4.3.1

.travis.yml, Gemfile, gemfiles/3.2.awsv1.gemfile, gemfiles/3.2.awsv2.0.gemfile, gemfiles/3.2.awsv2.1.gemfile, gemfiles/4.1.awsv1.gemfile, gemfiles/4.1.awsv2.0.gemfile, gemfiles/4.1.awsv2.1.gemfile, gemfiles/4.2.awsv1.gemfile, gemfiles/4.2.awsv2.0.gemfile, gemfiles/4.2.awsv2.1.gemfile
They are allowed to fail, and they consistently fail. They only add up
time to our builds. If we wanted to keep them, they should be in the
build matrix and run tests successfully.
=> Remove from Travis JRuby and Rubinius

paperclip.gemspec, spec/paperclip/storage/fog_spec.rb
There was a change in `aruba` that is breaking the cucumber tests. This PR doesn't fix the root problem, it just locks down the version to make it work. This partially addresses #2048 
The `fog` gem has been making updates to loosen dependencies on net-ssh (see fog/fog-core/pull/166 or fog/fog/commit/ebfaa0c97a387eeb18c5c797aaa33a1596e46676). Rather than explicitly requiring net-ssh this PR changes the development dependencies to the 2 providers that are tested.
=> Resolve broken CI tests due to upstream gem changes

lib/paperclip/attachment.rb, lib/paperclip/interpolations.rb, lib/paperclip/interpolations/plural_cache.rb, lib/paperclip/rails_environment.rb, lib/paperclip/storage/s3.rb, paperclip.gemspec, spec/paperclip/interpolations_spec.rb, spec/paperclip/plural_cache_spec.rb, spec/paperclip/storage/fog_spec.rb
This is a rebased PR of #1888 against the v4.3 branch. It also includes the gem dependency fixes from #2051 to get the build to green.
=> Cache interpolator methods and reduce memory allocations - rebased on v4.3

README.md
The reference on README was to `master` while there was not release for paperclip 4.3.2.
Since it was just released, the reference was updated.
=> Update README with version requirement for aws-sdk

paperclip.gemspec
File.exists? is deprecated and produces unecessary warning.
=> Replace File.exists? with File.exist? in paperclip.gemspec

lib/paperclip/schema.rb
These variables were introduced in:
https://github.com/thoughtbot/paperclip/commit/6ea7c26512434a
but their usage were canceled in:
https://github.com/thoughtbot/paperclip/commit/c740fb171fe
=> Remove unused vars `column_(type|options)` from `remove_attachment` method

Appraisals, Gemfile, gemfiles/4.2.awsv2.0.gemfile, gemfiles/4.2.awsv2.1.gemfile
- The specs pass for the bits related to mime-types. I don’t use Paperclip
otherwise, but there were a couple of local failures.
- Fix the appraisals, too.
- This will not fully work until mikel/mail is updated to support the same
restriction, but I have PR open to expand mime-types support there, currently
being reviewed for merge.
=> Modify the Gemfile for testing with mime-types 3

lib/paperclip/attachment.rb, spec/paperclip/attachment_spec.rb
The MD5 sum of an attachment is only necessary if the model has a corresponding `_fingerprint` column. If this column is absent, there is no need to calculate the MD5, which can be an expensive operation for large files.
Accomplish this by deferring the fingerprint calculation using a block. If the `_fingerprint` column is absent, the block is never called, and the calculation is avoided.
This issue was fixed once before (see #357, #696), but a subsequent refactor seems to have reintroduced the problem.
=> Skip calculating fingerprint when it is not used

spec/paperclip/paperclip_spec.rb, spec/spec_helper.rb, spec/support/rails_helpers.rb
Since support for Rails 3.2 was removed (https://github.com/thoughtbot/paperclip/pull/2074), those specs are not more needed
=> Remove attr_protected related specs (was removed in rails 4)

lib/paperclip.rb, lib/paperclip/deprecations.rb, spec/paperclip/deprecations_spec.rb, spec/paperclip/paperclip_spec.rb, spec/support/deprecations.rb
Following https://github.com/thoughtbot/paperclip/pull/2095
=> Add deprecation warnings for aws-sdk < 2 and active record < 4.2

lib/paperclip/deprecations.rb, spec/paperclip/deprecations_spec.rb, spec/support/deprecations.rb
As @kt0 noticed in #2098, my commit https://github.com/thoughtbot/paperclip/commit/2e6335532ac24012cf473b60994d09f14952b891 broke  compatibility for non ActiveRecord user.
Checking ActiveModel version instead of ActiveRecord fixes this since it's a paperclip dependency
=> Check ActiveModel instead of ActiveRecord for deprecations

NEWS, lib/paperclip/media_type_spoof_detector.rb, spec/paperclip/media_type_spoof_detector_spec.rb
Backport 8339e0f (#2017) to 4.3 to prevent excessive logging, which [might be abused](https://cwe.mitre.org/data/definitions/779.html). Fixes #2125. 
Please release 4.3.6 as soon as possible to prevent abuse.
=> Backport fix for excessive logging from media type spoof detector 

NEWS, lib/paperclip/storage/fog.rb, spec/paperclip/storage/fog_spec.rb
We found that uploading large files to S3 would result in a socket error ("connection reset by peer") occasionally and lately much more consistently. In researching this I saw that many people got this error when uploading too large of a file without multipart chunking. I would have assumed fog did this automatically but the default chunk size may be too high. In order to address this I wanted to drop the chunk size to 100MB.
Rather than hard-code this I opted to expose a `fog_option` configuration option that lets me pass any additional options I want to the fog's `#create` call. This is similar to the `fog_attributes` option implemented in CarrierWave which [addresses the same problem](http://stackoverflow.com/a/11867978/201911).
We've been running this now for a week in production and …
=> Add fog_options to configuration that can be passed to the fog

README.md, features/migration.feature, features/step_definitions/rails_steps.rb, lib/paperclip/schema.rb, spec/paperclip/attachment_spec.rb
Rails 3 is not supported anymore. We can safely remove mentions and
snippets for it.
=> Remove Rails 3 snippets

README.md, lib/paperclip/storage/s3.rb
Brings back warning on not supported SDK versions.
Related: https://github.com/thoughtbot/paperclip/commit/25be0b25d67923e28419c6146e8f8307741a974b#commitcomment-16831800
=> README update (AWS SDK version)

NEWS, lib/paperclip/storage/fog.rb, spec/paperclip/storage/fog_spec.rb
`Paperclip::Storage::Fog#host_name_for_directory` assumes a String-like object is set and doesn't check if `@options[:fog_directory]` is callable, while `Paperclip::Storage::Fog#directory` does. I would recommend extracting a new method with the condition and refactoring the other two methods to call it.
See https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/storage/fog.rb#L191 and https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/storage/fog.rb#L220
Fixes #2018.
=> Bugfix: Dynamic fog directory

lib/paperclip/attachment.rb
This was really confusing to me, and I think this small change would help to clarify what's going on without having to trace through the code.
=> Clarify semantics of the only_process option (documentation-only)

spec/paperclip/storage/s3_spec.rb
This is part of the effort started at https://github.com/thoughtbot/paperclip/issues/2199 to ensure the test suite is green locally.
This spec was failing on obtaining a S3 instance with an `nil` region key. Since `Aws::Resource` does a regex match against the region key passed in, we would fail on `NoMethodError`.
This corrects the issue by setting a region key to an empty string in the test setup.
=> Correct failing S3 storage spec

spec/paperclip/validators_spec.rb
This is part of the effort started at https://github.com/thoughtbot/paperclip/issues/2199 to ensure the test suite is green locally.
The validators spec was failing since the setup required was missing a call to 'rebuild_class' and leaving the Dummy class in a bad state.
This PR adds the call to the before block setup.
=> Correct validators spec

spec/paperclip/attachment_processing_spec.rb
This is part of the effort started at https://github.com/thoughtbot/paperclip/issues/2199 to ensure the test suite is green locally.
The attachment processing spec was failing since the setup required done in a before block, namely a call to `rebuild_class`, was running restricted to one of two contexts in the test file.
This was leaving the `Dummy` class in a bad state and affected other tests.
This PR moves the `before` block to run for the both of the contexts.
=> Correct attachment processing spec

NEWS, lib/paperclip/matchers/validate_attachment_content_type_matcher.rb, spec/paperclip/matchers/validate_attachment_content_type_matcher_spec.rb
When a matcher uses both `allowing` and `rejecting`, and validation fails, `@missing_rejected_types` might still be `nil`. The validation itself works as intended, but calling `failure_message` raises due to `@missing_rejected_types.any?`.
Presumably, this fixes #1334. Possibly also #1476.
---
I haven't added any tests for this fix yet. Any suggestions on what tests we would want? The minimal case would be:
```
expect{ matcher.failure_message }.not_to raise_error
```
But that feels dumb. On the other hand, testing the failure message string for some specific pattern feels like overkill. Ideas?
=> Fix a nil error in failure_message of content type validation matcher

NEWS, spec/paperclip/media_type_spoof_detector_spec.rb
This is the test from #2126 for the master branch.
=> Add test to prevent regression regarding excessive logging

.travis.yml, lib/paperclip/attachment.rb, lib/tasks/paperclip.rake, spec/paperclip/attachment_spec.rb
`value.present?` is more readable than `!value.blank?`. following this, 3 instances of `!value.blank?` have been replaced with `value.present?`
=> replaced 3 if-not-blank checks with if-present checks

README.md
Since the task `deploy` is quite exclusive to Capistrano, we should use Paperclip's own namespace instead, so not to be confused with Capistrano's `deploy`.
=> Use Paperclip namespace as Capistrano task

README.md
Missed out the deployment sequence in README.md after this merge https://github.com/thoughtbot/paperclip/commit/0eb3310410c5450b7fd265c7322487f757181b1d
@tute Please review again.
=> Update deployment sequence to paperclip namespace

NEWS, lib/paperclip.rb, lib/paperclip/io_adapters/uri_adapter.rb, spec/paperclip/io_adapters/uri_adapter_spec.rb
`Net::ReadTimeout` exception will occur if remote file couldn't be reached within default timeout.
This PR adds option `:read_timeout` to Paperclip to override default `open` timeout from UriAdapter download_content method.
#1923
=> Add read_timeout option to UriAdapter download_content method

spec/paperclip/storage/s3_spec.rb
AWS no longer accepts `:aes256` as an encryption value and will raise
`Aws::S3::Errors::InvalidArgument` with the message `The encryption method
specified is not supported`. It should instead be `"AES256"`.
This commit makes no implementation change, but for those that use
source code and tests as documentation, it should help prevent
confusion.
=> Update accepted server_side_encryption value

README.md
Before this change, the value for `preserve_files` was the string `"true"`, potentially confusing users that they should use stringified booleans like `"true"` and `"false"`.
However `"false"` would evaluate as truthy, and preserve files.
This appears to have been a factor in https://github.com/thoughtbot/paperclip/issues/1445#issuecomment-51430186
=> Update README preserve_files to be a boolean

NEWS, lib/paperclip/io_adapters/uri_adapter.rb, spec/paperclip/io_adapters/http_url_proxy_adapter_spec.rb, spec/paperclip/io_adapters/uri_adapter_spec.rb
@tute port from https://github.com/thoughtbot/paperclip/pull/2210
- The uri io adapter now seeks for the content-disposition header
if this is pressent the value filename is taken instead of the
last path segment for the resource file name
- Fix style comments
- Applied the Tute Costa refactor to URI Adapter.
- Added entry to  the NEWS file.
- Removed editor tracking file
- Fix test cases
=> [backport] The uri io adapter should use the content-disposition filename

README.md, lib/paperclip/io_adapters/abstract_adapter.rb, lib/paperclip/processor.rb, spec/paperclip/io_adapters/abstract_adapter_spec.rb
I recently implemented a custom processor that used [the Exifr gem](https://github.com/remvee/exifr) to extract EXIF information from images uploaded to a Paperclip attachment. Exifr's processor uses `readbyte` to parse the EXIF header, so it hit errors when Paperclip's `File`-like object didn't have one. There's also a test for this delegation. 
I've also tidied up the README documentation for custom processors, hopefully to be more clear than before. There was some duplicated content between the "Post Processing" section and the "Custom Attachment Processing" section, and those sections were separated in the file. I've dedicated the "Post Processing" section to Paperclip's built in thumbnailing processors, and made "Custom Attachment Processing" section solely about writing & using your …
=> Delegate #readbyte on the abstract IO adapter, and improve documentation around custom processors

README.md, lib/paperclip/interpolations.rb, lib/paperclip/storage/fog.rb, lib/paperclip/storage/s3.rb, lib/paperclip/validators.rb, spec/paperclip/validators_spec.rb
There's a subtle difference between what `\Z` and `\z` consider the "end of string" which is that the uppercase version allows a single trailing newline:
```ruby
/\Afoo\Z/.match("foo\n")
/\Afoo\Z/.match("foo\n\n")
/\Afoo\z/.match("foo\n")
```
The current usage of `\Z` / `\z` in the project can be discovered with:
```
$ git grep -iI "\\\z"
```
I've left the Cucumber steps alone as changing them makes adding the `has_attached_file` line fail.
=> Don't allow trailing newlines in various checks.

lib/paperclip/storage/s3.rb
[These lines](https://github.com/thoughtbot/paperclip/blob/95acf3b898bd782f4429d42fd2d8812505390328/lib/paperclip/storage/s3.rb#L101-L112) in the documentation indicated that the value for the `s3_storage_class` configuration option should be `:reduced_redundancy`. However, using this value with Paperclip 5.0.0 results in a `Aws::S3::Errors::InvalidStorageClass` error with the message `The storage class you specified is not valid`.
The [documentation for the `Aws::S3::Object#storage_class` method](http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Object.html#storage_class-instance_method) in the `aws-sdk` gem documentation indicates that the correct value is now `REDUCED_REDUNDANCY` (along with a few other potential values).
=> Updated documentation

lib/paperclip/io_adapters/abstract_adapter.rb, lib/paperclip/io_adapters/attachment_adapter.rb, lib/paperclip/storage/filesystem.rb
Paperclip duplicates the original files quite a lot as part of its validation process. (#1642, #1326).
When uploading large files (several hundred megabytes to gigabyte range), this becomes a problem: The web server will be busy creating 3 - 4 duplicates on disk, while the app (and potentially the user) are waiting for the upload operation to complete.
This pull request introduces hard links instead of ```FileUtil.cp``` where possible to keep the logic as-is but save time and disk space.
=> Instead of copying files in adapters, create hard links where possible

lib/paperclip/io_adapters/uploaded_file_adapter.rb, spec/paperclip/io_adapters/uploaded_file_adapter_spec.rb
This patch defaults `Paperclip::UploadedFileAdapter.content_type_detector` to `Paperclip::ContentTypeDetector`.
Without it, Paperclip allows the upload of any content, _including executables_, so long as the client forges a permitted content-type.
Security holes shouldn't be the default setting where we can avoid it.
=> Default to Paperclip::ContentTypeDetector

.codeclimate.yml, .hound.yml
Hello friends,
Earlier today, we unintentionally deleted this repository from Code Climate while doing some administrative cleanup. I'm really sorry this happened and please know we can get the data back if that's what you'd like, but we were wondering if you'd rather have the repository re-added using our new Platform.
The one hiccup is that your rubocop config is too old for our engine to use, so analyses on the new Platform don't succeed. This PR corrects that (and tries not to step on Hound in the process), making the repository suitable for adding again on Code Climate.
Please let me know what you think.
=> Add Code Climate Config

lib/paperclip/io_adapters/uri_adapter.rb
=> Ignore invalid Content-Disposition header

NEWS, README.md, lib/paperclip/attachment.rb, lib/paperclip/io_adapters/abstract_adapter.rb, lib/paperclip/io_adapters/attachment_adapter.rb, lib/paperclip/io_adapters/data_uri_adapter.rb, lib/paperclip/io_adapters/empty_string_adapter.rb, lib/paperclip/io_adapters/file_adapter.rb, lib/paperclip/io_adapters/http_url_proxy_adapter.rb, lib/paperclip/io_adapters/identity_adapter.rb, lib/paperclip/io_adapters/nil_adapter.rb, lib/paperclip/io_adapters/registry.rb, lib/paperclip/io_adapters/stringio_adapter.rb, lib/paperclip/io_adapters/uploaded_file_adapter.rb, lib/paperclip/io_adapters/uri_adapter.rb, lib/tasks/paperclip.rake, spec/paperclip/attachment_spec.rb, spec/paperclip/io_adapters/abstract_adapter_spec.rb, spec/paperclip/io_adapters/attachment_adapter_spec.rb, spec/paperclip/io_adapters/data_uri_adapter_spec.rb, spec/paperclip/io_adapters/file_adapter_spec.rb, spec/paperclip/io_adapters/http_url_proxy_adapter_spec.rb, spec/paperclip/io_adapters/identity_adapter_spec.rb, spec/paperclip/io_adapters/registry_spec.rb, spec/paperclip/io_adapters/stringio_adapter_spec.rb, spec/paperclip/io_adapters/uploaded_file_adapter_spec.rb, spec/paperclip/io_adapters/uri_adapter_spec.rb, spec/paperclip/storage/s3_spec.rb
This is the continuation of the work by @medcat in #1708. I've rebased his work on master and made separate commits addressing changes requested in that pull request. If the maintainers of the gem give the green light I will squash the commits (preserving authorship) for clean commit history 😄
=> Make fingerprints configurable to prepare for a new default in the future

lib/paperclip/attachment.rb, spec/paperclip/attachment_spec.rb
Bug introduced in 1c7d7f66ceea27cfe604e3a13c2eb87df217d13a
Per https://github.com/thoughtbot/paperclip/commit/1c7d7f66ceea27cfe604e3a13c2eb87df217d13a#commitcomment-18765681 request /cc @tute
=> Fixed only_process option with proc

README.md
header was [changed recently](https://github.com/thoughtbot/paperclip/commit/5202acbf4b642230bef71a8dd534bcca11fb4373#diff-04c6e90faac2675aa89e2176d2eec7d8L740), but link was not and now it's broken
=> fix broken anchor in README

lib/paperclip/storage/fog.rb, spec/paperclip/storage/fog_spec.rb
This mirrors the implementation for many other args including `fog_file`
=> Add support for proc arg for fog_public

lib/paperclip/storage/s3.rb
s3_permissions can no longer be a symbol. Must be a string.
Providing a string causes hard to debug errors in AWS.
As a side note, when these sorts of breaking changes occur to 
config I really think checks need to be put in place to validate
user input. Debugging this was time consuming as the errors
I was getting in no way made it obvious this was the problem.
N.B. I'm assuming that a change was made at some point to 
change s3_permissions from a symbol to a string. We were
previously using an older version of paperclip where this 
worked fine but when I updated this started failing.
=> Update docs for s3_permissions

spec/paperclip/tempfile_spec.rb, spec/paperclip/thumbnail_spec.rb
Was browsing the paperclip test suite and noticed that the `thumbnail_spec` had a few tests from a while back that did not belong - they were testing `Paperclip::Tempfile` instead.
This PR removes those tests.
=> Remove Tempfile tests from Thumbnail spec

.travis.yml, features/step_definitions/attachment_steps.rb, features/step_definitions/rails_steps.rb, features/support/paths.rb, features/support/rails.rb, paperclip.gemspec, spec/spec_helper.rb
- Removes `bundle exec` from commands ran in cucumber steps
- Simplifies `framework_major_version` (we can assume it always is 4 or higher)
=> Fix Travis CI

lib/paperclip/storage/filesystem.rb
Fixes the following warning shown by JRuby 9.1.6.0:
gems/paperclip-5.1.0/lib/paperclip/storage/filesystem.rb:49: warning: `&' after local variable or literal is interpreted as binary operator even though it seems like argument prefix
=> Fix JRuby binary operator warning

UPGRADING
I noticed an extra whitespace character in the layout, it looked ugly in the CLI when installing the gem.
=> Removed extra whitespace from UPGRADING

lib/tasks/paperclip.rake
Exception is the root of Ruby's exception hierarchy, so when you rescue Exception you rescue from everything, including subclasses such as SyntaxError, LoadError, and Interrupt etc which is a bad idea.
Fix: rescue from StandardError.
=> Remove bad exception handling!

.travis.yml, Gemfile, README.md, Rakefile, features/step_definitions/rails_steps.rb, features/step_definitions/s3_steps.rb, features/support/env.rb, gemfiles/4.2.gemfile, gemfiles/5.0.gemfile, lib/paperclip/io_adapters/attachment_adapter.rb, lib/paperclip/io_adapters/data_uri_adapter.rb, lib/paperclip/io_adapters/empty_string_adapter.rb, lib/paperclip/io_adapters/file_adapter.rb, lib/paperclip/io_adapters/http_url_proxy_adapter.rb, lib/paperclip/io_adapters/identity_adapter.rb, lib/paperclip/io_adapters/nil_adapter.rb, lib/paperclip/io_adapters/registry.rb, lib/paperclip/io_adapters/stringio_adapter.rb, lib/paperclip/io_adapters/uploaded_file_adapter.rb, lib/paperclip/io_adapters/uri_adapter.rb, spec/paperclip/io_adapters/data_uri_adapter_spec.rb, spec/paperclip/io_adapters/http_url_proxy_adapter_spec.rb, spec/paperclip/io_adapters/uri_adapter_spec.rb, spec/paperclip/storage/s3_spec.rb
Remove the URI adapters. Few people use them by default and they can allow insight into the internal networks of the server. If you want to enable them, add (for example) `Paperclip.DataUriAdapter.register` to your `config/initializers/paperclip.rb` file.
Additional note: this needs to be documented, but comments welcome as to where and how.
=> No uri adapters

NEWS, lib/paperclip/version.rb
This is a year in the making, with a security patch motivating it.
[ci skip]
=> Prepare release 5.2.0

lib/paperclip/io_adapters/abstract_adapter.rb
When I try to attach a file on Windows Paperclip fails on trying to make a link with Errno::EEXIST exception.
This exception should be caught as others inside `Paperclip::AbstractAdapter#link_or_copy_file`
=> Add Errno::EEXIST as possible exception that happens on linking

README.md
Hey folks, just noticed a few little inconsistencies in the README code style while setting up a new project. Thanks for all your hard work on this great library!
=> Use consistent code style in README examples

lib/generators/paperclip/paperclip_generator.rb, lib/generators/paperclip/templates/paperclip_migration.rb.erb
[Relevant Issue](https://github.com/thoughtbot/paperclip/issues/2465) : Rails 5 does not allow classes to inherit directly from ActiveRecord::Migration without specifying a version. This prevents basic actions such as `db:migrate`.
If the rails version is >= 5.x, pass a `migration_version` variable to the `migration_template` function to ensure that `[5.x]` is appended to the migration function declaration.
For similar code from a more trusted source, see [Devise's implementation](https://github.com/plataformatec/devise/blob/master/lib/generators/active_record/devise_generator.rb#L14).
Hey there's no test for this change! But there are no tests for any of the paperclip generator functions. It's late maybe I'll write em later.
=> Add migration_version variable to migration generator for rails 5 compatibility

README.md
`convert_options` and `source_file_options` are great tools, but I had to find out about them through Stack Overflow. I think they deserve a spot in the README. Keep up your awesome work!
=> Updated Post Processing Documentation to mention convert_options and source_file_options

lib/paperclip/storage/s3.rb
Gives an example, since not everyone knows the format required.
=> Docs: Provide example for s3_host_name

lib/paperclip/url_generator.rb
fix missing dependency on delegator in Rails. Not sure how to test it, because all active support core extensions are loaded in spec_helper
```
2.3.1 :003 > require 'paperclip'
NoMethodError: undefined method `delegate' for Paperclip::UrlGenerator:Class
Did you mean?  DelegateClass
from /Users/lordvacuumcleaner/paperclip/lib/paperclip/url_generator.rb:21:in `<class:UrlGenerator>'
from /Users/lordvacuumcleaner/paperclip/lib/paperclip/url_generator.rb:4:in `<module:Paperclip>'
from /Users/lordvacuumcleaner/paperclip/lib/paperclip/url_generator.rb:3:in `<top (required)>'
from /Users/lordvacuumcleaner/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /Users/lordvacuumcleaner/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:5 …
```
=> fix missing dependency when running  require paperclip in irb

README.md
The command from the README is often copied into projects directly. The version used here before had a known vulnerability (CVE-2017-0889), so it might be wise to mention something more secure instead.
=> Update the README Installation section

lib/paperclip/io_adapters/abstract_adapter.rb, spec/paperclip/io_adapters/abstract_adapter_spec.rb
Combining implementation in https://github.com/thoughtbot/paperclip/pull/2559 and spec coverage in https://github.com/thoughtbot/paperclip/pull/2540 to close https://github.com/thoughtbot/paperclip/issues/2558
=> symlink failure bug fixes

lib/paperclip/storage/fog.rb, spec/paperclip/storage/fog_spec.rb
There was a bug in the code where if you created a bucket the file would
get read but not rewind on the first pass through (when the bucket
didn't exist). So when we went into the retry logic the file would
already be read and zero bytes would get copied over from the file. This
fixes that by rewinding the file during the retry so it gets correctly
copied over the second time around.
=> Rewind file in Storage::Fog if bucket does not exist

lib/paperclip.rb, lib/paperclip/file_command_content_type_detector.rb, lib/paperclip/geometry_detector_factory.rb, lib/paperclip/helpers.rb, lib/paperclip/media_type_spoof_detector.rb, lib/paperclip/thumbnail.rb, paperclip.gemspec, spec/paperclip/content_type_detector_spec.rb, spec/paperclip/file_command_content_type_detector_spec.rb, spec/paperclip/paperclip_spec.rb, spec/paperclip/processor_spec.rb, spec/paperclip/thumbnail_spec.rb
Cocaine has been renamed to Terrapin (ref https://github.com/thoughtbot/cocaine/issues/99).
This Pull Request replaces `Cocaine::` with `Terrapin::`.
=> Replace cocaine to terrapin

MIGRATING.md
A start at an introductory migration path for moving from Paperclip to
[ActiveStorage].
ActiveStorage is coming in Rails 5.2 (April, perhaps) and we want to
help people move from Paperclip to it. Having a file upload strategy
baked into Rails itself will allow us all to focus our efforts and
follow a common goal.
This migration guide is rudimentary at best: it works for a `User`
object with one `avatar` attachment. It is provided as a framework to
start the documentation.
I have tried this in a dummy app.
[ActiveStorage]: http://edgeguides.rubyonrails.org/active_storage_overview.html
=> A migration guide from Paperclip to ActiveStorage

lib/paperclip/io_adapters/http_url_proxy_adapter.rb, spec/paperclip/io_adapters/http_url_proxy_adapter_spec.rb
Closes #2253.
Allow `HttpUrlProxyAdapter` to handle already-escaped targets by calling `URI.escape` only when necessary (since the latter *isn't* idempotent).
=> 2253 handle url encoded

README.md
Remove content type object in AttachmentContentTypeValidator.
=> Fix content type in docs

lib/paperclip/storage/fog.rb
So that the `file_system` option renders correctly on the docs
=> Fix markdown typo

lib/paperclip/io_adapters/abstract_adapter.rb, spec/paperclip/io_adapters/abstract_adapter_spec.rb
This is necessary for:
```
$ uname -a
Linux aki-X220t 4.15.1-2-ARCH #1 SMP Sun Feb 4 22:27:45 UTC 2018 x86_64 GNU/Linux
$ mount -l | grep /tmp
tmpfs on /tmp type tmpfs (rw,relatime)
```
=> Reopen file even when copying instead of linking

lib/paperclip/attachment.rb, spec/paperclip/attachment_spec.rb, spec/support/model_reconstruction.rb
This validation was causing issue when there is no content_type column in the database, as the content type of the attachment would be empty. There should be no need to check attachment's validity because this `#reprocess!` method is running internally on the server.
Fix #2078
=> Skip validity check when reprocess attachment

MIGRATING.md
The Paperclip -> ActiveStorage migration guide was referencing the recommended validation gem incorrectly so I've updated it
Additionally, there were backticks around the `key` value in the active_storage_blobs SQL that were causing the migration to error out when trying to run it
This PR addresses both of those issues
=> Fix a couple of typos in the migration guide

MIGRATING.md
The official [RSpec documentation](https://relishapp.com/rspec/rspec-expectations/v/2-4/docs/custom-matchers/define-matcher#define-a-matcher-with-default-messages) outlines that the main block when defining custom matchers should be called `match`. 
The documentation currently uses `matches` when giving an example of the custom `:have_attached_file` matcher, which leads to the error 
NoMethodError:
undefined method `matches' for #<Class:#<RSpec::Matchers::DSL::Matcher:0x00007fc898c846d8>>
Updating to `match`
=> Migration Documentation: RSpec custom matcher, use `match` not `matches`

README.md
We were contacted in early December by Surendra of Kreeti, who explained
that they had forked Paperclip and were maintaining it. We let the
December US holidays go by and then checked in; they're still
maintaining it.
We do not know any of the Kreeti devs and cannot vouch for them as a
team. We did not know of a way to hand over the Rubygem ownership while
expressing that people should remember to audit when upgrading.
Therefore, we felt it best that they have a full fork: new Rubygem gem,
separate repo.
Therefore it makes sense for us to link to Kreeti's fork as an option
for those who cannot move off of Paperclip.
=> Link to kt-paperclip
